#!/usr/bin/env bash

# to use:######################################################################
# - run `source [thisfile]` at the top of your script
# - set these two variables to either nothing, or 1
#   - opt_db
#   - opt_vb
###############################################################################

###############################################################################
# commonly used shell scripting functions
###############################################################################

#colors:
#TOOD: wrap this "color" block in if statement in case run to a log file
col_end='\033[0m' #cap
col_blk='\e[0;30m'
col_red='\e[1;31m'
col_grn='\e[1;32m'
col_ylw='\e[1;33m'
col_blu='\e[1;34m'
col_wht='\e[0;37m'

#these rely on opt_db and opt_vb booleans
if_debug() { (( $opt_db > 0)) && return 0 || return 1; }
if_verbose() { (( $opt_vb > 0)) && return 0 || return 1; }

printer() {
  echo -e "${col_grn}::${col_end} ${@}"
}

stamp() {
  printer "$(date --rfc-3339=seconds) ${col_ylw}::${col_end} ${@}"
}

warn() {
  echo -e "${col_ylw}::${col_end} ${col_red}WARNING:${col_end} ${@}"
}

err() {
  echo -e "${col_ylw}::${col_end} ${col_red}ERROR:${col_end} ${@}" >&2
}

verb() {
  if_verbose || return
  echo -e "${col_ylw}::${col_end} ${@}"
}

dbg() {
  if_debug || return
  echo -e "${col_ylw}::${col_end} ${col_blu}DEBUG:${col_end} ${@}"
}
