#!/bin/bash

timeout_default=240 # default 4 hours

# to load keys on this machine setup in ~/.ssh/add/:
# lrwxrwxrwx   jzlut.add -> ../jzlut
# lrwxrwxrwx   jzlut.add.pub -> ../jzlut.pub

#################################################################

if [[ $1 = '-h' || $1 = '--help' ]];then
    echo -e "usage: -t [timeout] [keys ... ]
    \tkeys are ssh key pairs to \`ssh-add\` to the agent
    \tdefault: all keys from ~/.ssh/add/*.add.
    \ttimeout is minutes for key to last
    \tdefault: $timeout_default ($(( $timeout_default / 60 )) hours).
    \t[see keychain(1)]" >&2
    exit 2
else [[ $1 == '-t' ]];then
    passed=$1
    shift
fi

timeout=${passed:-$timeout_default}

key_add() {
    for key  in ; do
        eval $(keychain --eval --timeout $timeout ~/.ssh/add/*.add ${@})
    done
}

# key_add && source ~/.keychain/$HOSTNAME-sh || exit 1
if [[ key_add ]]; then
    source ~/.keychain/$HOSTNAME-sh
else
    echo 'failed to `addkeys` to ssh-agent! see keychain(1)' >&2
    exit 1
fi
