#!/usr/bin/env bash

declare -a AVAIL
_n=$(basename $0)

#@TODO: make this check both OSX/Linux locations.
while read dir;do
  AVAIL+=(${dir/*-/ })
done < <(find /usr/local/ -maxdepth 1 -type d -name 'netbeans-*')
unset dir

usage() {
  local avail
  IFS='|'
  avail="${AVAIL[*]/./}"
  _n="\`$_n'"

  printf "Wrapper around netbeans...
  usage: %s [version] [ /path/to/filename ]

  eg.:   %s [%s] [ ~/my/little/pony.txt ]
" "$_n" "$_n" "$avail" >&2
  exit 1
}

#check for help
[[ $1 = -h || $1 = --help ]] && usage

# pick a netbeans version to launch
shgl=$(shopt -p extglob)
shopt -s extglob
if (( ${#1} == 2 )) && [[ ${1} = +([[:digit:]]) ]];then
  ver=$1
  shift
else
  ver=${BEANS_VERSION:-'70'}
fi
$shgl #set back whatever you had

ver=${ver:0:1}.${ver:1}
netbeans="/usr/local/netbeans-${ver}/bin/netbeans"

if [[ -r $netbeans ]];then
  level="FINE"
  parse="-J-Dorg.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.level=$level"
  $netbeans "$parse" "${@}" >& /dev/null & disown
else
  IFS=,
  avail="${AVAIL[*]/./}"

  printf "ERROR: Netbeans v.:%s not available.
    Only found versions %s\n" "${ver}" "$avail" >&2
  exit 1
fi

# vim: et:ts=2:sw=2
