#!/usr/bin/env bash

#get the current time
analog=({00..59})
h=${analog[ 10#$(date +%H) ]}
m=${analog[ 10#$(date +%M) ]}
s=${analog[ 10#$(date +%S) ]}

while true; do
    #need one space to avoid your cursor.
    printf ' %s\r' "${h}:${m}:${s}"
    if (( $(( 10#$s )) == 59 ));then
        s=${analog[0]}
        if (( $(( 10#$m )) == 59 ));then
            m=${analog[0]}
            if (( $(( 10#$h )) == 23 ));then
                h=${analog[0]}
            else
                h=${analog[$(( $(( 10#$h )) + 1 ))]}
            fi
        else
            m=${analog[$(( $(( 10#$m )) + 1 ))]}
        fi
    else
        s=${analog[$(( $(( 10#$s )) + 1 ))]}
    fi
    sleep 1s
done
