#!/usr/bin/env bash

DOC_URI=$1
BAK_DIR=$2

DOC_PRE='todo_'
DOC_SUF='.pad.bak'
## CHANGE ABOVE STRING VALUES, ONLY: #############################################

usage() {
    echo "usage: \`$(basename $0)'  ETHERPAD_TEXT_URI BACKUP_DIR" >&2
    exit 2
}

(( $# != 2 )) && usage
[[ -w "$BAK_DIR" ]] || {
    printf 'Error: backup directory,"%s", not writeable.\n' "$BAK_DIR" >&2
    exit 2
}

backup() {
    curl -s "$DOC_URI" > "$BAK_DIR/${DOC_PRE}$(date --rfc-3339=date)_$(date +%s)${DOC_SUF}"
    (( $? )) && echo "backup failed, \`curl\` exited with $?" >&2 || return 0
}

#only backup if necessary
latest_bak=$(find "$BAK_DIR" -name "${DOC_PRE}*${DOC_SUF}" | sort | tail -n 1)
diff <(curl -s "$DOC_URI") "$latest_bak" >&/dev/null || backup

# vim: et:sw=4:ts=4
