#!/bin/bash
# easy "project" searching

if [[ -z $PROJECT_BASE ]];then
    echo '$PROJECT_BASE env var not set.' >&2
    exit 1
fi

if (( $# < 1));then
    echo 'usage: identical to grep, without the path' >&2
    exit 2
fi

# declare -p CB #debug

#grep "$@" $PROJECT_BASE/sites/all/{modules/{features,custom},themes/zagat}
grep "$@" ${CB[@]}
