#!/bin/bash

find \
  /srv/http/subs/notes/www/sites/all/modules/contrib/ \
  /srv/http/subs/notes/www/includes/ \
  /srv/http/subs/notes/www/sites/all/themes/ \
  /srv/http/subs/notes/www/modules/ \
  \( -name '*.inc' -or -name '*.php' -or -name '*.module' \)  > ~/.vim/cscope.files

cscope -i ~/.vim/cscope.files
rm  ~/.vim/cscope.files
