#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 3 && "$#" -ne 4 ]];then
  printf 'usage: BAD_EMAIL CORRECT_EMAIL CORRECT_NAME [GIT_REV_RANGE]

  GIT_REV_RANGE defaults to entire history (--all)
  specifying it must be in the form of a commit OR ref, followed by two dots,
  followed by a ref only (not a commit), eg: 26d5472d27b3b40..HEAD is valid.
' >&2
  exit 1
fi

declare -r wrongEmail="$1"
declare -r replaceWithMail="$2"
declare -r replaceWithName="$3"

# eg: 26d5472d27b3b40..HEAD
declare -r targetDefault='-- --all'
target="${4:-$targetDefault}"

printf -v filter -- \
    'if [ "$%s" = "%s" ];then %s="%s"; export "%s"; %s="%s"; export "%s"; fi' \
    GIT_AUTHOR_EMAIL "$wrongEmail" \
    GIT_AUTHOR_EMAIL "$replaceWithMail" GIT_AUTHOR_EMAIL \
    GIT_AUTHOR_NAME  "$replaceWithName" GIT_AUTHOR_NAME

set -x
git filter-branch -f --env-filter "$filter" $target
