#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 3 && "$#" -ne 4 ]];then
  printf 'usage: BAD_EMAIL CORRECT_EMAIL CORRECT_NAME [GIT_REV_RANGE]\n' >&2
  exit 1
fi

declare -r wrongEmail="$1"
declare -r replaceWithMail="$2"
declare -r replaceWithName="$3"

# eg: master...b38fee0ef9a12
declare -r targetDefault='--all'
target="${4:-$targetDefault}"

printf -v filter -- \
    'if [ "$%s" = "%s" ];then %s="%s"; export "%s"; %s="%s"; export "%s"; fi' \
    GIT_AUTHOR_EMAIL "$wrongEmail" \
    GIT_AUTHOR_EMAIL "$replaceWithMail" GIT_AUTHOR_EMAIL \
    GIT_AUTHOR_NAME  "$replaceWithName" GIT_AUTHOR_NAME

git filter-branch -f --env-filter "$filter" -- "$target"
