#!/usr/bin/env bash
set -euo pipefail

declare -r defaultDisplay=':0'
declare -r autoDesk=auto_desktop.jpg
declare -r autoLogn=auto_login.jpg

bgrndsDir="$(readlink -f "$1")"; declare -r bgrndsDir
[[ -d "$bgrndsDir" && -r "$bgrndsDir" ]] || {
  printf 'warn: no bgrnds dir at: %s\n' "$1" >&2
  exit 0
}
picsDir="$(xdg-user-dir PICTURES)"; declare -r picsDir
[[ "$picsDir" != "$HOME" ]] || {
  printf 'error: failed to load xdg-user dir "PICTURES"\n' >&2
  exit 1
}

cd "$picsDir"

if [[ -e "$autoDesk" && -r "$autoDesk" ]];then
  currentDesk="$(basename "$(readlink -f "$autoDesk")")"
fi
if [[ -e "$autoLogn" && -r "$autoLogn" ]];then
  currentLogn="$(basename "$(readlink -f "$autoLogn")")"
fi

findRandImgNot() (
  local invertMatch; invertMatch="$1"
  local numBgrnds randBgrnd randIdx unused
  mapfile -t unused < <(
    find "$bgrndsDir" -mindepth 1 -maxdepth 1 -type f -print |
        grep --extended-regexp --invert-match "$invertMatch" |
        sort
  )
  numBgrnds="${#unused[@]}"

  if (( numBgrnds == 0 ));then
    printf 'warning: no alternative desktop images to install. exiting...\n' >&2
    exit
  fi

  # integer in [1,$numBgrnds]
  randIdx="$(shuf --input-range "0-$(( numBgrnds - 1 ))" --head-count 1)"

  printf '%s' "${unused[$randIdx]}"
)

randDsktp="$(findRandImgNot "$currentDesk"'$')"
randLogin="$(findRandImgNot "$currentLogn"'$')"

ln --force --symbolic --verbose "$randDsktp" "$autoDesk"
ln --force --symbolic --verbose "$randLogin" "$autoLogn"
