#!/usr/bin/env bash
set -euo pipefail

declare -r defaultDisplay=':0'

bgrndsDir="$(readlink -f "$1")"; declare -r bgrndsDir
[[ -d "$bgrndsDir" && -r "$bgrndsDir" ]] || {
  printf 'no bgrnds dir at: %s\n' "$1" >&2
  exit 1
}
picsDir="$(xdg-user-dir PICTURES)"; declare -r picsDir
[[ "$picsDir" != "$HOME" ]] || {
  printf 'error: failed to load xdg-user dir "PICTURES"\n' >&2
  exit 1
}

currentBgrnd="$(
  gsettings get org.gnome.desktop.background picture-uri |
    sed --expression 's|file://||' \
        --expression "s|^'||" \
        --expression "s|'$||"
)"
declare -r currentBgrnd

findRandImgNot() (
  local invertMatch; invertMatch="$1"
  local numBgrnds randBgrnd randIdx unused
  mapfile -t unused < <(
    find "$bgrndsDir" -mindepth 1 -maxdepth 1 -type f -print |
        grep --extended-regexp --invert-match "$invertMatch" |
        sort
  )
  numBgrnds="${#unused[@]}"

  if (( numBgrnds == 0 ));then
    printf 'warning: no alternative desktop images to install. exiting...\n' >&2
    exit
  fi

  # integer in [1,$numBgrnds]
  randIdx="$(shuf --input-range "0-$(( numBgrnds - 1 ))" --head-count 1)"

  printf '%s' "${unused[$randIdx]}"
)

randDsktp="$(findRandImgNot "$currentBgrnd"'$')"
randLogin="$(
  desktop="$(basename randDsktp)"
  findRandImgNot "${currentBgrnd}|${desktop}"'$'
)"

cd "$picsDir"
ln --force --symbolic --verbose "$randDsktp" auto_desktop.jpg
ln --force --symbolic --verbose "$randLogin" auto_login.jpg
