#!/usr/bin/env bash

~/.host/common/away

i3lock \
  --nofork \
  --tiling \
  --pointer=default \
  --show-failed-attempts \
  --image="$HOME"/media/img/wallpaper/lockscreen-sleeping.png

~/.host/common/seated
