#!/usr/bin/env bash
#
# Call irssi/weechat, but stop me if my config is out of date, first.
#
#   Note this is purposely a script and not a shell function, as I want `tmux`
#   to execute *this* logic for me when it reloads from saved sessions.
set -e

declare -r ircClient="$(
  if [ -n "$IRC" ];then
    echo "$IRC"
  else
    if type weechat >/dev/null 2>&1;then
      echo weechat
    elif type irssi >/dev/null 2>&1;then
      echo irssi
    else
      printf 'Cannot find an IRC client to use\n' >&2
      exit 2
    fi
  fi
)"
if [ "$ircClient" = weechat ];then
  declare -r latest=~/.weechat/irc.conf.default
  declare -r current=~/.weechat/irc.conf
elif [ "$ircClient" = irssi ];then
  declare -r latest=~/.irssi/config.default
  declare -r current=~/.irssi/config
else
  printf 'ERROR: zomg, bug in this script\n' >&2
  exit 3
fi

declare -A clr=(
  [end]='\033[0m'
  [blk]='\e[0;30m'
  [red]='\e[1;31m'
  [grn]='\e[1;32m'
  [ylw]='\e[1;33m'
  [blu]='\e[1;34m'
  [wht]='\e[0;37m'
)
col() { _clr=$1; shift; echo -en "${clr[$_clr]}$@${clr[end]}"; }

cmpr() {
  local diffExec=diff
  if type colordiff >/dev/null 2>&1;then diffExec=colordiff;fi

  "$diffExec" --unified --show-c-function \
    <(\grep --invert-match password "$latest") \
    <(\grep --invert-match password "$current");
}
if ! cmpr > /dev/null 2>&1; then
  {
    printf \
      '\n%s:    %s config differs from your dotfiles in "%s"\n\n' \
      "$(col ylw WARNING)" \
      "$ircClient" \
      "\$$(printf "$latest" | sed -e "s|$HOME|HOME|")"
    cmpr;
  } | "${PAGER:-less}"
  echo; read -p "Run "$ircClient" with $(col red old config) anyway? [yN] " answer
  ans="${answer,,}"; ans="${ans:0:1}"
  if [ "$ans" != y ];then
    printf \
      '\n%s %s, run `%s` again when fixed\n' \
      "$(col grn GREAT)" \
      'giving you your shell back' \
      "$(basename "$(readlink -f "${BASH_SOURCE[0]}")")" >&2
    exit 1
  fi
fi

"$ircClient"
