#!/usr/bin/env bash
set -euo pipefail

this="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"; declare -r this
[[ "$#" -eq 0 ]] || (
  printf 'usage: %s

  Quickly start taking notes in focused environment.

  Launches $EDITOR on a new asciidoc under xdg-dir DOCUMENTS, pre-populates it
  with a date and title, assumes $EDITOR is some vim derivative and tries to
  launch it with Goyo[1] (the zenroom plugin launch command)

  [1]: https://github.com/amix/vim-zenroom2
' "$this" >&2
  exit 1
)

docsDir="$(xdg-user-dir DOCUMENTS)"; declare -r docsDir

printf -v mktemp_temp '%s_%s_XXXXXX.adoc' "$this" "$(date --iso-8601=d)"
jotDoc="$(mktemp --tmpdir="$docsDir" "$mktemp_temp")"; declare -r jotDoc
printf '= Jot Doc Started %s\n%s <%s>\nv0.0.1, %s\n\n' \
  "$(date --iso-8601=ns)" \
  "$(getent passwd "$(whoami)" | cut -f 5 -d : | sed -e 's|,*$||g')" \
  "$EMAIL" \
  "$(date --iso-8601=d)" > "$jotDoc"
printf '$EDITOR launching:\n%s\n\n' "$jotDoc"

hashOfDoc() ( md5sum < "$1" | cut -f 1 -d ' '; )
baseHash="$(hashOfDoc "$jotDoc")"; declare -r baseHash
cleanupNothingJotted() (
  local currentHash; currentHash="$(hashOfDoc "$jotDoc")"
  [[ "$baseHash" = "$currentHash" ]] || return 0
  printf 'Nothing jotted, removing doc...\n' >&2
  rm -v "$jotDoc"
)
trap cleanupNothingJotted EXIT

"$EDITOR" "$jotDoc" +:Goyo +:SyntasticToggleMode
