#!/usr/bin/env python
import urllib2
import getpass

#global conf:
class ImporterAccounts:
    def __init__(self):
        self.accts=('Checking' 'Saving')

class ImporterTdbank(ImporterAccounts):
    """Handle import of various TDBank banking accounts."""
    def __init__(self, usr=getpass.getuser(), pas=None):
        self.creds = {'usr': usr}
        self.bank = {
            'name': 'TD Bank',
            'url': 'https://onlinebanking.tdbank.com/',
            #make this whole structure come in via conf files.
        }
        self.creds['pas'] = None #learn python's getopts and make this possible

    def prompt_creds(self):
        print 'Please enter your credentails (press ENTER for [default] values)'
        self.creds['usr'] = raw_input('username ["%s"]: ' % (self.creds['usr']))
        self.creds['pas'] = getpass.getpass('password: ')

    def http_post_request(self):
        s = urllib2.urlopen(self.bank['url'])
        html = s.read()
        s.close()
        print html

if __name__ == '__main__':
    tdbank = ImporterTdbank()
    print 'Getting exports for "%s"...' % (tdbank.bank['name'])
