#!/usr/bin/env bash

# run the appropriate lint on all files in our working directory which are
# waiting to be staged, regardless of VCS of choice or filetype that's been
# changed.

#
#default options from env.
#
c_lint="${LINT_PHP:-no default}"
cpp_lint="${LINT_PHP:-no default}"
js_lint="${LINT_ECMA:-jshint}"
java_lint="${LINT_JAVA:-no default}"
php_lint="${LINT_PHP:-php -a}"
py_lint="${LINT_PYTHON:-no default}"


#
# sanity check
#
_n="$(basename "$0")"
if (( $# ));then
  #we take no options

  printf "
  Summary
    \`%s\`, Lint any outstanding changes in your working tree, assuming you're
    in a VCS repository of  some kind..

  Lint parsers can be specified via the following env. variables:
    LINT_C\t(default: %s)
    LINT_CPP\t(default: %s)
    LINT_JAVA\t(default: %s)
    LINT_ECMA\t(default: %s)
    LINT_PHP\t(default: %s)
    LINT_PYTHON\t(default: %s)
\n" "${_n,,}" \
  "$c_lint" \
  "$cpp_lint" \
  "$js_lint" \
  "$java_lint" \
  "$php_lint" \
  "$py_lint" >&2
  exit 1
fi

#
#vcs-related functions
#
which_vcs() {
  if [[ $(hg root 2>/dev/null) ]];then
    printf 'hg'
  elif [[ $(git status 2>/dev/null) ]];then
    printf 'git'
  fi
}

hg_root() {
  echo 'gah running hg root' >&2 # //@TODO: remove me!!    
  printf "%s" "$(hg root)"
}

git_root() {
  printf "%s" "$(git rev-parse --show-toplevel)"
}

hg_changed() {
  hg status -n
}

git_changed() {
  git status --porcelain | sed -e 's/^\ .[[:space:]]*//'
# while read changes; do
#   echo "$changes" | sed -e 's/^\ .[[:space:]]*//'
# done < <(git status --porcelain)
}

#
#linting-related functions
# (the only real logic in this script)
#
lint() {
  local f="$1" ftype
  echo "TODO: running lint on ${f}" >&2
  if [[ "${f/*.}" = js ]];then
    $(js_lint "$f")
  else
    ftype="$(file -b "$f")"
    ftype="${ftype/ */}"
    case ${ftype,,} in
      php)
        $(php_lint "$f")
        ;;
      *)
        printf 'Could not determine linter for filetype: %s\n\t[file: %s]\n' \
          "${ftype,,}" "$f" >&2
        return 1
        ;;
    esac
  fi
}

#
#dynamic bits (making use of above functions:
#
vcs="$(which_vcs)"
changed="${vcs}_changed"
echo "vcs, seems to be: $vcs" >&2 # //@TODO: remove me!!    
echo "vcs_root command will be: ${vcs}_root" >&2 # //@TODO: remove me!!    
vcs_root="${vcs}_root"
echo "hg_root, returns: $(hg_root)" >&2 # //@TODO: remove me!!    
echo "vcs_root, evaluated: $("${vcs}_root")" >&2 # //@TODO: remove me!!    
echo "vcs_root, definitive: $vcs_root" >&2 # //@TODO: remove me!!    
exit 99 #//@TODO: remove me!!    

#
# actually run our linter over our files:
#

while read file; do
  command lint "${vcs_root}/${file}"
  echo '... finished linting file...' >&2 # //@TODO: remove me!!    
done < <($("$changed"))

