#!/usr/bin/env bash

# while [ true ];
# do {
#   for i in /var/log/*.log\
#     /var/log/syslog\
#     /var/log/mysql\
#     /var/log/messages\
#     /var/log/dmesg\
#     $HOME/docs/logs/*.log;
#   do
#     sz=$(stat --printf="%s%b" ${i})
#     if (( $sz > 0 ));then
#       clear && printf "\n\nLOGS:\t%s\n" ${i}
#       timeout 15 tail -f -n 30 ${i}; 2>/dev/null
#     fi
#   done
# };
# done

tail -f $(find $HOME/docs/log{,s} /var/log/ -name '*.log')
