#!/usr/bin/env bash
#
# Sets random wallpaper from $XDG_PICTURES_DIR or $1 subdirectory under it
set -euo pipefail

dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
feh --bg-fill "$("$dir"/minwm_randimg $@)"
