#!/usr/bin/env bash

_n="$(basename "$0")"
musicdir="$(readlink -f "$1")"
[[ -r "$musicdir" && -d "$musicdir" ]] || {
  printf 'Error: "%s" is not a readable directory\n' "$musicdir" >&2
  printf 'USAGE: %s MUSIC_DIR\n' "$_n" >&2
  exit 1
}

{ type mplayer >/dev/null 2>&1 && playerExc=mplayer; } ||
  { type mpv >/dev/null 2>&1 && playerExc=mpv; } ||
    { printf 'could not find something to playback video with\n' >&2; exit 2; }

"$playerExc" -playlist <(find "$musicdir" -type f | sort)
