#!/usr/bin/env bash

_n="$(basename "$0")"
musicdir="$(readlink -f "$1")"
[[ -r "$musicdir" && -d "$musicdir" ]] || {
  printf 'Error: "%s" is not a readable directory\n' "$musicdir" >&2
  printf 'USAGE: %s MUSIC_DIR\n' "$_n" >&2
  exit 1
}
mplayer -playlist <(find "$musicdir" -type f | sort)
