#!/usr/bin/env bash

WATCH="${1:-$HOME/pub/drop}"
INOTIFY='http://github.com/rvoicilas/inotify-tools'
LIBNOTIFY='http://www.galago-project.org'
depends=(inotifywait notify-send)
HEADER="Someone Just Touched: $WATCH"

usage() {
    echo -e "
    Continuously watch a file (or directory) and notify you of changes using
    using libnotify. You most likely will want to background this process and
    run it as a daemon.

    usage: $(basename $0) [file_name ...]
        where file_name is the name of a dile or directory you'd like to be
        notified of changes to.

        eg.: \`$(basename $0) ~/pub/drop\`

    NOTE:
        Multiple filename arguments has not been tested with this script.
        See: notify-send(1) $INOTIFY
        See: inotifywait(1) $LIBNOTIFY
    " >&2
    exit 2
}

dependency() {
    echo -e "'$1' not found.\nPlease install all dependencies to this script." >&2
    usage
    exit 3
}

#for friends who don't like reading source code:
if [[ $1 = '--help' || $1 = '-h' ]];then
    usage
fi

#for the same friends
for util in ${depends[@]}; do
    type -p "$util" >&/dev/null || dependency "$util"
done


# if inotifywait is passed a non-existent directory,
# it goes into a monsterous infinate loop instead of failing.
if [[ -r $WATCH ]];then
    recurse='--recursive'
else
    echo "Error: cannot find '$WATCH' in filesystem" >&2
    exit 3
fi

# the actual magic:
while read -r message; do
    notify-send "$message"
done <(inotifywait
    --recursive \
    --monitor \
    --event delete \
    --event move \
    --event create \
    --event modify \
    --timefmt='%H:%M:%S' \
    --format='%T (%e) | "%f"' "$WATCH")

# vim: et:sw=4:ts=4
