#!/usr/bin/env bash
#
# Script to run updates, intended for manual execution.
set -o errexit
set -o nounset
set -o pipefail

declare -a aptCommands=(
  update
  upgrade
  update
  dist-upgrade
  update
#Dangerous, may leave me w/o quick/easy rollback:
# autoclean
# autoremove
); declare -r aptCommands

#####################################

# STEP 1: Backup current system state
if [[ $# -eq 0 ]] || [[ "$1" != --no-backup ]];then
  sudo ~/bin/share/borgw_system.sh /mnt/localbackups/"$(hostname)"
else
  echo 'WARNING: not backing up before modifying system!' >&2
fi

# STEP 2: Actually move further along bleeding edge
time (
  set -x
  for act in "${aptCommands[@]}"; do
    sudo apt-get "$act"
  done
) 2>&1 | tee -a ~/usr/log/bleeding-update.log
