#!/usr/bin/env bash
#
# Script to run updates, intended for manual execution.
set -o errexit
set -o nounset
set -o pipefail

declare -a aptCommands=(
  update
  upgrade
  update
  dist-upgrade
  update
#Dangerous, may leave me w/o quick/easy rollback:
# autoclean
# autoremove
); declare -r aptCommands

highlight() ( \grep --extended-regexp --color=always "$1"; )
teeLog() ( tee -a ~/usr/log/bleeding-update.log; )
this="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"; declare -r this
#####################################

# STEP 0: Log Beginning/end of this script
log() (
  printf '[%s | %s] %s\n' "$(date --iso-8601=ns)" "$this" "$*" |
    highlight "$this" |
    teeLog
)
trap 'log FINISHED' EXIT
log STARTING

# STEP 1: Backup current system state
if [[ $# -eq 0 ]] || [[ "$1" != --no-backup ]];then
  sudo ~/bin/share/borgw_system.sh /mnt/localbackups/"$(hostname)"
else
  log 'WARNING: not backing up before modifying system!' >&2
fi

# STEP 2: Actually move further along bleeding edge
time (
  set -x
  for act in "${aptCommands[@]}"; do
    sudo apt-get "$act"
  done
) 2>&1 | teeLog
