#!/usr/bin/env bash
#
# Try to guess whether target is an archive or text file 

declare -r target="$1"

use_pygmentize() {
  local termOpt=''
  if echo "$TERM" | grep -E '256|tmux' >/dev/null 2>&1;then
    # For more, see /usr/share/doc/python-pygments/formatters.html
    termOpt=' -f terminal256 '
  fi
  pygmentize -g $termOpt "$target"
}

use_sourceHighlight() {
  source-highlight --data-dir "${TMP:-/tmp}"/"src-highlight.$$" "$target"
}

isTargetBinary() {
  file --dereference --mime-encoding --brief "$target" 2>/dev/null |
    grep binary >/dev/null 2>&1
}

haveExec() ( type "$1" >/dev/null 2>&1; )
isHighlighterAvailable() { haveExec pygmentize || haveExec source-highlight; }

if isTargetBinary || ! isHighlighterAvailable;then
  lesspipe "$target"
else
  if haveExec pygmentize;then
    use_pygmentize
  elif haveExec source-highlight;then
    use_sourceHighlight
  fi
fi
