#!/usr/bin/env bash
#
# Run all env. `export` statements
#
# NOTE: This is intended to be run from inside ~/.bashrc (yes, nested shells).

isAlreadyExported() {
  printf "${!1}" | tr : '\n' | grep "^${2}$" > /dev/null 2>&1
}

# Hacks to somewhat allow "export ENV=...." to be run a million times without
# making a mess.
#
# $1=env var to export (eg: PYTHONPATH)
# $@=strings to colon-delimited prepend (eg: /my/pylib /sys/pylib)
exportPrependedOnce() {
  local env_var="$1";shift

  local to_prepend="$(
    local -a found=( $(printf "${!env_var}" | tr : '\n') )
    local isFirst=1

    local part
    for part in $@; do
      printf '%s\n' "${found[@]}" | grep "$part" >/dev/null 2>&1 &&
          continue

      (( isFirst )) || printf ':'
      isFirst=0

      printf '%s' "$part"
    done
  )"

  [ -z "$to_prepend" ] && return  # nothing new

  local toExport="$to_prepend"
  [ -n "${!env_var}" ] && toExport="$toExport:"${!env_var}""

  export "${env_var}=$toExport"
}


# Static/vanilla (not appending) env vars:
export XDG_CONFIG_HOME=$HOME/.config
export CSCOPE_DB=$HOME/.vim/cscope.out
export COWER='cower --color=auto'
export BROWSER=w3m
export SHOT_PUB='shot'
export SHOT_UPLOAD='ompload'
export TTS_CONFIG=~/.ttskeyrc
export PASTIE='dpaste'
export EDITOR=vim
export DIFF=' up '
export LESS=' XFRr '
export RLWRAP=' AaN '
export PAGER=less
export RUBYOPT='w' #helpful ruby warnings
export GREP_OPTIONS='--color=auto'
export GOPATH="$HOME/usr/lib/go/"
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk-amd64/'
export GRADLE_USER_HOME="$XDG_CONFIG_HOME"/gradle/

exportPrependedOnce 'PATH' \
  "$HOME/bin" \
  "$HOME/bin/local" \
  "$HOME/bin/share" \
  "$HOME/bin/dist" \
  "$HOME/bin/lib" \
  "$HOME/usr/lib/go/bin" \
  "$JAVA_HOME/bin" \
  "$HOME/usr/local/bin/android/sdk/platform-tools" \
  "$HOME/usr/local/bin/android/sdk/tools" \
  "$HOME/usr/local/bin/android/studio/bin" \
  "/usr/local/go/bin"

exportPrependedOnce 'CLASSPATH' "$HOME/var/edu/princenton/algs4"
exportPrependedOnce 'PYTHONPATH' "$HOME/usr/lib/python"
exportPrependedOnce 'NODE_PATH' \
  "/usr/local/lib/node_modules" \
  "/usr/lib/node"


unset isAlreadyExported
unset concatWithColons
unset exportPrependedOnce
